POST {{$dotenv HOST_URL}}/api/auth/register
Content-Type: application/json

{
  "email": "staff6@alexandrebekor.com",
  "username": "alexandrebekor",
  "password": "123456"
}

###
POST {{$dotenv HOST_URL}}/api/auth/login
Content-Type: application/json

{
  "email": "staff@alexandrebekor.com",
  "password": "123456"
}