# @name signUp
POST {{$dotenv HOST_URL}}/api/auth
Content-Type: application/json

{
  "email": "staff7@alexandrebekor.com",
  "username": "alexandrebekor",
  "password": "123456"
}

###
# @name signIn
POST {{$dotenv HOST_URL}}/api/login
Content-Type: application/json

{
  "email": "staff@alexandrebekor.com",
  "password": "123456"
}
###
@token = {{signIn.response.body.token}}

# @name profile
GET {{$dotenv HOST_URL}}/api/me
Authorization: Bearer {{token}}

###
# @name getUserProfile
GET {{$dotenv HOST_URL}}/api/me
Authorization: Bearer {{token}}

###
# @name getAllRepositories
GET {{$dotenv HOST_URL}}/api/users/1587649/repos
Authorization: Bearer {{token}}